### ISSUE TITLE
 NoMethodError: undefined method `options' for #<ActiveSupport::Callbacks::Callback:0x007fc2ca992bb0>

### ISSUE THREAD

**Issue by zauzaj** [jdliss/shoulda-callback-matchers#27]
Hi,

After upgrading Rails from 4.1.14 to 4.2, I'm getting this error in my specs
consultation.rb
```
after_commit :schedule_staff_notifier, on: :create, if: :persisted?
```

consultation_spec.rb
```
it { expect(consultation).to callback(:schedule_staff_notifier).after(:commit).on(:create) }
```
```
 NoMethodError:
    undefined method `options' for #<ActiveSupport::Callbacks::Callback:0x007fc2ca992bb0>
```
Activesupport version is `4.2.0`. 

Previously it did work normally.

Is there any way to solve it? 

Regards
